base_model: mistralai/Mistral-7B-Instruct-v0.3
prompt_template_name: mistral
opt_type: simple
data_root: data
train_file: all_data/train.jsonl
learning_rate: 1.0e-4
num_epochs: 1
batch_size: 128
micro_batch_size: 1
cutoff_len: 4096
warmup_ratio: 0.1
lr_scheduler: cosine
optim: adamw_torch
seed: 42
train_on_inputs: false
add_eos_token: false
group_by_length: false
gradient_checkpointing: false
load_in_8bit: false
buffer_capacity: 5000
replay_ratio: 0.2
buffer_update_strategy: task-balanced
new_limit: 20000
combo_limit: 2000
val_limit: 0
save_step_records: true
wandb_project: ""
wandb_run_name: ""
wandb_watch: ""
wandb_log_model: ""
