base_config: base.yaml
method: naive_sequence
output_root: outputs/cl_train/naive_sequence
steps:
  step1:
    new_tasks: [drd2]
    combo_tasks: []
  step2:
    new_tasks: [qed]
    combo_tasks: [drd2+qed]
  step3:
    new_tasks: [plogp]
    combo_tasks: [drd2+qed+plogp]
  step4:
    new_tasks: [jnk3]
    combo_tasks: [drd2+qed+plogp+jnk3]
